# Generated by Django 2.2.2 on 2019-09-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
